disabled_rules:
- identifier_name
- trailing_whitespace
- trailing_comma
- line_length
- void_return

excluded:
- Carthage
- Pods

force_cast:
severity: warning

force_try:
severity: warning

type_body_length:
warning: 300
error: 400

file_length:
warning: 500
error: 1200
